name: Persimmon Versioning

on:
  pull_request:
    branches: 
      - main
    types:
      - closed
   


jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 

   

    - name: Get the latest tag
      id: get_latest_tag
      run: |
        latest_tag=$(git for-each-ref --sort=-creatordate --format='%(refname)' | grep '^refs/tags/')
        if [[ -n "$latest_tag" ]]; then

          latest_tag=$(echo "$latest_tag" | head -n 1 | cut -d '/' -f 3)
          echo "Latest tag: $latest_tag"


        else
        echo "No tags found"
        fi

        latest_tag="${latest_tag#v}"
        echo "Latest tag: $latest_tag"

        IFS='.' read -ra version <<< "$latest_tag"
        
        MAJOR="${version[0]}"
        MINOR="${version[1]}"
        PATCH="${version[2]}"

        echo "TAG: $latest_tag"
        echo "version: ${version[@]}"
        echo "MAJOR: $MAJOR"
        echo "MINOR: $MINOR"
        echo "PATCH: $PATCH"

        PATCH=$((PATCH + 1))

        # Create the new version
        NEW_VERSION="${MAJOR}.${MINOR}.${PATCH}"
      
        echo "Latest version is: $NEW_VERSION"

        

      


   




        
      
        
         
  




        
        
        






