name: Persimmon Versioning

on:
  pull_request:
    branches: 
      - main
    types:
      - closed
   


jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 

   

    - name: Get the latest tag
      id: get_latest_tag
      env:
        MY_EMAIL: amars123456@gmail.com
        MY_NAME: amardeepio
        
      run: |
        git config --global user.email $MY_EMAIL
        git config --global user.name $MY_NAME
        
        latest_tag=$(git for-each-ref --sort=-creatordate --format='%(refname)' | grep '^refs/tags/')
        echo "Raw tags: $latest_tag"
        if [[ -n "$latest_tag" ]]; then
          latest_tag=$(echo "$latest_tag" | grep -oP 'v[0-9]+\.[0-9]+\.[0-9]+$')
          echo "Filtered tags: $latest_tag"
          if [[ -n "$latest_tag" ]]; then
            echo "Latest tag: $latest_tag"
            # Proceed with the rest of the steps using the filtered tag
          else
            echo "No tags found in the desired format"
            exit 1  # Fail the job if no tags in the desired format are found
          fi
        else
          echo "No tags found"
          exit 1
        fi
     

        latest_tag="${latest_tag#v}"
        echo "Latest tag: $latest_tag"

        IFS='.' read -ra version <<< "$latest_tag"
        
        MAJOR="${version[0]}"
        MINOR="${version[1]}"
        PATCH="${version[2]}"

        echo "TAG: $latest_tag"
        echo "version: ${version[@]}"
        echo "MAJOR: $MAJOR"
        echo "MINOR: $MINOR"
        echo "PATCH: $PATCH"

        PATCH=$((PATCH + 1))

        # Create the new version
        NEW_VERSION="${MAJOR}.${MINOR}.${PATCH}"
      
        echo "Latest version is: $NEW_VERSION"

        # create the new tag 

        git tag -a -m "Incrementing patch version to $NEW_VERSION" "$NEW_VERSION"

        #push the tags

        git push origin "$NEW_VERSION"



        
