name: Persimmon Versioning

on:
  pull_request:
    branches: 
      - main
    types:
      - closed
   


jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 

   

    - name: Get the latest tag
      id: get_latest_tag
      run: echo echo ::set-output name=TAG::$(git describe --tags --abbrev=0)


         
