name: Persimmon Versioning

on:
  pull_request:
    branches: 
      - main
    types:
      - closed
   


jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 

    - name: Get Latest Tag
      id: version

      run: |
      

        
          # Get the latest tag
          latest_tag=$(git describe --tags --abbrev=0)

          # Extract the major, minor, and patch versions
          major=$(echo $latest_tag | cut -d. -f1)
          minor=$(echo $latest_tag | cut -d. -f2)
          patch=$(echo $latest_tag | cut -d. -f3)

          # Increment the patch version
          new_patch=$((patch + 1))

          # Set the new version
          new_version="$major.$minor.$new_patch"
          echo "::set-output name=new_version::$new_version"

   
         
