name: Persimmon Versioning

on:
  pull_request:
    branches: 
      - main
    types:
      - closed
   


jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 

    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v5.3.0
      with:
        
        tag_prefix: "v"
        version_format: "${major}.${minor}.${increment}"

    - name: Get next version
      uses: reecetech/version-increment@2023.9.3
      id: version
      with:

        scheme: semver
        increment: patch
         
