name: Persimmon Versioning

on:
  pull_request:
    branches: 
      - main
    types:
      - closed
   


jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 

   

    - name: Get the latest tag
      id: get_latest_tag
      env:
        MY_EMAIL: ${{ secrets.MY_EMAIL }}
        MY_NAME: ${{ secrets.MY_NAME }}
        
      run: |
        git config  user.email $MY_EMAIL
        git config  user.name $MY_NAME
        
        
        latest_tag=$(git for-each-ref --sort=-creatordate --format='%(refname)' | grep -oP 'refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$')
        if [[ -n "$latest_tag" ]]; then
          latest_tag=$(echo "$latest_tag" | sed 's|^refs/tags/||')  # Remove the 'refs/tags/' prefix
          echo "Latest tag: $latest_tag"
        else
          echo "No tags found in the desired format"
          exit 1  # Fail the job if no tags in the desired format are found
        fi

        latest_tag="${latest_tag#v}"
        echo "Latest tag: $latest_tag"

        IFS='.' read -ra version <<< "$latest_tag"
        
        MAJOR="${version[0]}"
        MINOR="${version[1]}"
        PATCH="${version[2]}"

        echo "TAG: $latest_tag"
        echo "version: ${version[@]}"
        echo "MAJOR: $MAJOR"
        echo "MINOR: $MINOR"
        echo "PATCH: $PATCH"

        PATCH=$((PATCH + 1))

        # Create the new version
        NEW_VERSION="${MAJOR}.${MINOR}.${PATCH}"
      
        echo "Latest version is: $NEW_VERSION"

        # create the new tag 

        git tag -a -m "Incrementing patch version to $NEW_VERSION" "$NEW_VERSION"

        #push the tags

        git push origin "$NEW_VERSION"
