name: Persimmon Versioning

on:
  pull_request:
    branches: 
      - main
    types:
      - closed
   


jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 

   

    - name: Get the latest tag
      id: get_latest_tag
      run: |
        latest_tag=$(git for-each-ref --sort=-creatordate --format='%(refname)' | grep '^refs/tags/')
        if [[ -n "$latest_tag" ]]; then

          latest_tag=$(echo "$latest_tag" | head -n 1 | cut -d '/' -f 3)
          echo "Latest tag: $latest_tag"


        else
        echo "No tags found"
        fi

        latest_tag="${latest_tag#v}"
        echo "Latest tag: $latest_tag"


    - name: Increment patch number
      id: increment_patch_number
      run: |
        major=$(echo "$latest_tag" | cut -d '.' -f 1)
        minor=$(echo "$latest_tag" | cut -d '.' -f 2)
        patch=$(echo "$latest_tag" | cut -d '.' -f 3)
        new_patch=$((patch + 1))

        new_version="$major.$minor.$(printf "%02d" $new_patch)"
        echo "New version: $new_version"

       
         
  




        
        
        






